extends: existence
message: "ClickHouse server settings '%s' should be enclosed in backticks."
level: suggestion
ignorecase: true
tokens:
  -'dictionary_background_reconnect_interval'
  -'show_addresses_in_stack_traces'
  -'shutdown_wait_unfinished_queries'
  -'shutdown_wait_unfinished'
  -'max_thread_pool_size'
  -'max_thread_pool_free_size'
  -'thread_pool_queue_size'
  -'max_io_thread_pool_size'
  -'max_io_thread_pool_free_size'
  -'io_thread_pool_queue_size'
  -'max_prefixes_deserialization_thread_pool_size'
  -'max_prefixes_deserialization_thread_pool_free_size'
  -'prefixes_deserialization_thread_pool_thread_pool_queue_size'
  -'max_fetch_partition_thread_pool_size'
  -'max_active_parts_loading_thread_pool_size'
  -'max_outdated_parts_loading_thread_pool_size'
  -'max_unexpected_parts_loading_thread_pool_size'
  -'max_parts_cleaning_thread_pool_size'
  -'max_mutations_bandwidth_for_server'
  -'max_merges_bandwidth_for_server'
  -'max_replicated_fetches_network_bandwidth_for_server'
  -'max_replicated_sends_network_bandwidth_for_server'
  -'max_remote_read_network_bandwidth_for_server'
  -'max_remote_write_network_bandwidth_for_server'
  -'max_local_read_bandwidth_for_server'
  -'max_local_write_bandwidth_for_server'
  -'max_backups_io_thread_pool_size'
  -'max_backups_io_thread_pool_free_size'
  -'backups_io_thread_pool_queue_size'
  -'backup_threads'
  -'max_backup_bandwidth_for_server'
  -'restore_threads'
  -'shutdown_wait_backups_and_restores'
  -'cannot_allocate_thread_fault_injection_probability'
  -'max_connections'
  -'asynchronous_metrics_update_period_s'
  -'asynchronous_metrics_enable_heavy_metrics'
  -'asynchronous_heavy_metrics_update_period_s'
  -'default_database'
  -'tmp_policy'
  -'max_temporary_data_on_disk_size'
  -'temporary_data_in_cache'
  -'aggregate_function_group_array_max_element_size'
  -'aggregate_function_group_array_action_when_limit_is_reached'
  -'max_server_memory_usage'
  -'max_server_memory_usage_to_ram_ratio'
  -'merges_mutations_memory_usage_soft_limit'
  -'merges_mutations_memory_usage_to_ram_ratio'
  -'allow_use_jemalloc_memory'
  -'cgroups_memory_usage_observer_wait_time'
  -'cgroup_memory_watcher_hard_limit_ratio'
  -'cgroup_memory_watcher_soft_limit_ratio'
  -'async_insert_threads'
  -'async_insert_queue_flush_on_shutdown'
  -'ignore_empty_sql_security_in_create_view_query'
  -'max_build_vector_similarity_index_thread_pool_size'
  -'database_atomic_delay_before_drop_table_sec'
  -'database_catalog_unused_dir_hide_timeout_sec'
  -'database_catalog_unused_dir_rm_timeout_sec'
  -'database_catalog_unused_dir_cleanup_period_sec'
  -'database_catalog_drop_error_cooldown_sec'
  -'database_catalog_drop_table_concurrency'
  -'max_concurrent_queries'
  -'max_concurrent_insert_queries'
  -'max_concurrent_select_queries'
  -'max_waiting_queries'
  -'cache_size_to_ram_max_ratio'
  -'uncompressed_cache_policy'
  -'uncompressed_cache_size'
  -'uncompressed_cache_size_ratio'
  -'mark_cache_policy'
  -'mark_cache_size'
  -'mark_cache_size_ratio'
  -'mark_cache_prewarm_ratio'
  -'primary_index_cache_policy'
  -'primary_index_cache_size'
  -'primary_index_cache_size_ratio'
  -'primary_index_cache_prewarm_ratio'
  -'vector_similarity_index_cache_policy'
  -'vector_similarity_index_cache_size'
  -'vector_similarity_index_cache_max_entries'
  -'vector_similarity_index_cache_size_ratio'
  -'index_uncompressed_cache_policy'
  -'index_uncompressed_cache_size'
  -'index_uncompressed_cache_size_ratio'
  -'index_mark_cache_policy'
  -'index_mark_cache_size'
  -'index_mark_cache_size_ratio'
  -'page_cache_block_size'
  -'page_cache_history_window_ms'
  -'page_cache_policy'
  -'page_cache_size_ratio'
  -'page_cache_min_size'
  -'page_cache_max_size'
  -'page_cache_free_memory_ratio'
  -'page_cache_lookahead_blocks'
  -'page_cache_shards'
  -'mmap_cache_size'
  -'compiled_expression_cache_size'
  -'compiled_expression_cache_elements_size'
  -'query_condition_cache_policy'
  -'query_condition_cache_size'
  -'query_condition_cache_size_ratio'
  -'disable_internal_dns_cache'
  -'dns_cache_max_entries'
  -'dns_cache_update_period'
  -'dns_max_consecutive_failures'
  -'dns_allow_resolve_names_to_ipv4'
  -'dns_allow_resolve_names_to_ipv6'
  -'max_table_size_to_drop'
  -'max_partition_size_to_drop'
  -'max_table_num_to_warn'
  -'max_pending_mutations_to_warn'
  -'max_view_num_to_warn'
  -'max_dictionary_num_to_warn'
  -'max_database_num_to_warn'
  -'max_part_num_to_warn'
  -'max_table_num_to_throw'
  -'max_replicated_table_num_to_throw'
  -'max_dictionary_num_to_throw'
  -'max_view_num_to_throw'
  -'max_database_num_to_throw'
  -'max_authentication_methods_per_user'
  -'concurrent_threads_soft_limit_num'
  -'concurrent_threads_soft_limit_ratio_to_cores'
  -'concurrent_threads_scheduler'
  -'background_pool_size'
  -'background_merges_mutations_concurrency_ratio'
  -'background_merges_mutations_scheduling_policy'
  -'background_move_pool_size'
  -'background_fetches_pool_size'
  -'background_common_pool_size'
  -'background_buffer_flush_schedule_pool_size'
  -'background_schedule_pool_size'
  -'background_message_broker_schedule_pool_size'
  -'background_distributed_schedule_pool_size'
  -'tables_loader_foreground_pool_size'
  -'tables_loader_background_pool_size'
  -'async_load_databases'
  -'async_load_system_database'
  -'display_secrets_in_show_and_select'
  -'keep_alive_timeout'
  -'max_keep_alive_requests'
  -'replicated_fetches_http_connection_timeout'
  -'replicated_fetches_http_send_timeout'
  -'replicated_fetches_http_receive_timeout'
  -'total_memory_profiler_step'
  -'total_memory_tracker_sample_probability'
  -'total_memory_profiler_sample_min_allocation_size'
  -'total_memory_profiler_sample_max_allocation_size'
  -'validate_tcp_client_information'
  -'storage_metadata_write_full_object_key'
  -'max_materialized_views_count_for_table'
  -'max_database_replicated_create_table_thread_pool_size'
  -'database_replicated_allow_detach_permanently'
  -'format_alter_operations_with_parentheses'
  -'default_replica_path'
  -'default_replica_name'
  -'disk_connections_soft_limit'
  -'disk_connections_warn_limit'
  -'disk_connections_store_limit'
  -'storage_connections_soft_limit'
  -'storage_connections_warn_limit'
  -'storage_connections_store_limit'
  -'http_connections_soft_limit'
  -'http_connections_warn_limit'
  -'http_connections_store_limit'
  -'global_profiler_real_time_period_ns'
  -'global_profiler_cpu_time_period_ns'
  -'enable_azure_sdk_logging'
  -'max_entries_for_hash_table_stats'
  -'merge_workload'
  -'mutation_workload'
  -'throw_on_unknown_workload'
  -'series_keeper_path'
  -'prepare_system_log_tables_on_startup'
  -'config_reload_interval_ms'
  -'memory_worker_period_ms'
  -'memory_worker_correct_memory_tracker'
  -'memory_worker_use_cgroup'
  -'disable_insertion_and_mutation'
  -'parts_kill_delay_period'
  -'parts_kill_delay_period_random_add'
  -'parts_killer_pool_size'
  -'keeper_multiread_batch_size'
  -'use_legacy_mongodb_integration'
  -'license_key'
  -'prefetch_threadpool_pool_size'
  -'prefetch_threadpool_queue_size'
  -'load_marks_threadpool_pool_size'
  -'load_marks_threadpool_queue_size'
  -'threadpool_writer_pool_size'
  -'threadpool_writer_queue_size'
  -'iceberg_catalog_threadpool_pool_size'
  -'iceberg_catalog_threadpool_queue_size'
  -'allow_feature_tier'
  -'dictionaries_lazy_load'
  -'wait_dictionaries_load_at_startup'
  -'storage_shared_set_join_use_inner_uuid'
