---
# Base Markdownlint configuration (Used by GitLab, modified where necessary for ClickHouse)
# Extended Markdownlint configuration in scripts/.markdownlint/
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for explanations of each rule
config:
  # First, set the default
  default: false
  MD040: true # Fenced code blocks should have a language specified
  links-url-type: true

  # Keep this item last due to length
  proper-names:                     # MD044
    code_blocks: false
    html_elements: false
    names: [
      # add Proper Names to ignore on capitalization check here
    ]
ignores:
  # add ignored directories here
  - "docs/ru"
  - "docs/zh"
  - "docs/en/whats-new"
customRules:
 # add custom rules here
  - "./markdownlint/rules/links_url_type.js"


