---
# Base Markdownlint configuration (Used by GitLab, modified where necessary for ClickHouse)
# Extended Markdownlint configuration in scripts/.markdownlint/
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for explanations of each rule
config:
  # turn settings on or off here
  default: false
  MD007: true # Unordered list indentation
  MD010: true # Disallow hard tabs
  MD012: true # Multiple consecutive blank lines
  MD040: true # Fenced code blocks should have a language specified
  #MD047: true # New line on end of file
  links-url-type: false # Disallow relative links to a .md or .mdx file
  custom-anchor-headings: true # Headings must have a custom anchor which is unique per page eg. # A Heading {#a-heading}
  no-markdown-image-tags: false
  # Keep this item last due to length
  proper-names: # MD044
    code_blocks: false
    html_elements: false
    names: []
# add Proper Names to ignore on capitalization check here
ignores:
  # add or remove ignored directories here
  - "docs/ru"
  - "docs/zh"
  - "docs/whats-new"
  - "docs/_placeholders"
  - "docs/operations/settings/settings.md" # autogenerated
  - "docs/operations/settings/settings-formats.md" # autogenerated
  - "docs/use-cases/AI_ML/MCP/index.md" # autogenerated
  - "docs/chdb/guides/index.md" # autogenerated
  - "docs/about-us/beta-and-experimental-features.md" # asutogenerated
  - "docs/getting-started/index.md" # autogenerated
  - "docs/cloud/manage/jan2025_faq/index.md" # autogenerated
  - "docs/cloud/reference/release-notes-index.md" # autogenerated
  - "docs/_placeholders"
  - "docs/cloud/manage/api"
  - "docs/use-cases/AI_ML/MCP/ai_agent_libraries/index.md" # autogenerated
  - "docs/sql-reference/functions" # autogenerated
  - "docs/cloud/reference/changelog.md"
customRules:
  # add custom rules here
  - "./markdownlint/custom_rules/links_url_type.js"
  - "./markdownlint/custom_rules/headings_have_custom_anchors.js"
  
