name: CLA Approval Handler

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to approve CLA for'
        required: true
        type: string
  pull_request:
    types: [labeled]

permissions: write-all

jobs:
  process-cla-approval:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'cla-signed'

    steps:
      - name: Debug - Event info
        run: |
          echo "=== CLA APPROVAL DEBUG ==="
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Manual trigger - PR: ${{ github.event.inputs.pr_number }}"
          else
            echo "Label: ${{ github.event.label.name }}"
            echo "Added by: ${{ github.actor }}"
            echo "PR number: ${{ github.event.number }}"
          fi
          echo "================================="

      - name: Generate Token
        id: generate-token
        continue-on-error: true
        uses: actions/create-github-app-token@v1
        with:
          app-id: "${{ secrets.WORKFLOW_AUTH_PUBLIC_APP_ID }}"
          private-key: "${{ secrets.WORKFLOW_AUTH_PUBLIC_PRIVATE_KEY }}"

      - name: Process CLA approval
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token || secrets.GITHUB_TOKEN }}
          script: |
            console.log('=== PROCESSING CLA APPROVAL ===');
            console.log('Event:', context.eventName);
            console.log('Actor:', context.actor);
            
            let prNumber;
            
            // Determine PR number
            if (context.eventName === 'workflow_dispatch') {
              prNumber = parseInt('${{ github.event.inputs.pr_number }}');
              console.log('Manual trigger for PR:', prNumber);
            } else if (context.eventName === 'pull_request') {
              prNumber = context.payload.pull_request.number;
              console.log('Label trigger for PR:', prNumber);
              console.log('Label added:', context.payload.label.name);
            } else {
              console.log('Unexpected event type, skipping...');
              return;
            }
            
            console.log('Processing CLA approval for PR:', prNumber);
            
            // Get PR details
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            
            console.log('PR author:', pr.user.login);
            
            // Check if the person triggering has the right permissions
            try {
              const { data: collaboration } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: context.actor
              });
            
              console.log('Actor permission level:', collaboration.permission);
            
              // Only admin, maintain, or write permissions can approve CLA
              const isAuthorized = ['admin', 'maintain', 'write'].includes(collaboration.permission);
              console.log('Is authorized to approve CLA:', isAuthorized);
            
              if (!isAuthorized) {
                console.log('User does not have permission to approve CLA');
            
                // If this was a label event, remove the label
                if (context.eventName !== 'workflow_dispatch') {
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: prNumber,
                    name: 'cla-signed'
                  });
                }
            
                // Add a comment explaining why the action was blocked
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  body: `@${context.actor} Only repository maintainers can approve CLAs. ${context.eventName !== 'workflow_dispatch' ? 'The label has been removed.' : ''}`
                });
            
                console.log('Unauthorized approval attempt blocked');
                return;
              }
            
              // Check if PR has cla-required label
              const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber
              });
            
              const hasClaMeeded = labels.some(label => label.name === 'cla-required');
              console.log('PR has cla-required label:', hasClaMeeded);
            
              if (!hasClaMeeded) {
                console.log('PR does not have cla-required label, no action needed');
                return;
              }
            
              // Ensure cla-signed label is present
              const hasClaSigned = labels.some(label => label.name === 'cla-signed');
              if (!hasClaSigned) {
                console.log('Adding cla-signed label...');
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  labels: ['cla-signed']
                });
              }
            
              // Authorized - proceed with approval
              console.log('Processing authorized CLA approval...');
            
              // Remove the blocking label
              try {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  name: 'cla-required'
                });
                console.log('Removed cla-required label');
              } catch (e) {
                console.log('cla-required label not found or already removed:', e.message);
              }
            
              // Check if confirmation comment already exists
              const comments = await github.rest.issues.listComments({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
            
              const confirmationExists = comments.data.some(comment => 
                (comment.user.login === 'github-actions[bot]' || comment.user.type === 'Bot') && 
                comment.body.includes('CLA Agreement Confirmed')
              );
            
              if (!confirmationExists) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  body: `## CLA Agreement Confirmed
            
              The trademark license agreement has been approved for @${pr.user.login}.
            
              **Status:** Approved  
              **Date:** ${new Date().toISOString()}  
              **Approved by:** @${context.actor}
              **Method:** ${context.eventName === 'workflow_dispatch' ? 'Manual approval' : 'Label approval'}
            
              This PR is now unblocked and can proceed with normal review!`
                });
                console.log('Posted confirmation comment');
              }
            
              console.log('CLA approval completed successfully');
            
            } catch (error) {
              console.error('Error processing CLA approval:', error);
              throw error;
            }
            
            console.log('=== END CLA APPROVAL PROCESSING ===');
