name: Integrations - trademark license

on:
  pull_request:
    types: [opened, edited, synchronize]
  issue_comment:
    types: [created, edited]

# Set repository-level permissions
permissions: write-all

jobs:
  enforce-docs-cla:
    runs-on: ubuntu-latest
    # Job-level permissions (inherits from above but can be more restrictive)
    permissions: write-all

    steps:
      - name: Debug - Check if secrets exist
        run: |
          echo "=== SECRET CHECK ==="
          if [ -z "${{ secrets.WORKFLOW_AUTH_PUBLIC_APP_ID }}" ]; then
            echo "WORKFLOW_AUTH_PUBLIC_APP_ID is empty or not set"
          else
            echo "WORKFLOW_AUTH_PUBLIC_APP_ID is set"
          fi
          
          if [ -z "${{ secrets.WORKFLOW_AUTH_PUBLIC_PRIVATE_KEY }}" ]; then
            echo "WORKFLOW_AUTH_PUBLIC_PRIVATE_KEY is empty or not set"
          else
            echo "WORKFLOW_AUTH_PUBLIC_PRIVATE_KEY is set"
          fi
          
          if [ -z "${{ secrets.GITHUB_PAT }}" ]; then
            echo "GITHUB_PAT is empty or not set"
          else
            echo "GITHUB_PAT is set"
          fi
          echo "==================="

      - name: Generate Token
        id: generate-token
        continue-on-error: true
        uses: actions/create-github-app-token@v1
        with:
          app-id: "${{ secrets.WORKFLOW_AUTH_PUBLIC_APP_ID }}"
          private-key: "${{ secrets.WORKFLOW_AUTH_PUBLIC_PRIVATE_KEY }}"

      - name: Debug - Token generation result
        run: |
          echo "=== TOKEN GENERATION RESULT ==="
          echo "Token step outcome: ${{ steps.generate-token.outcome }}"
          if [ "${{ steps.generate-token.outcome }}" = "success" ]; then
            echo "GitHub App token generated successfully"
          else
            echo "GitHub App token generation failed - will use GITHUB_TOKEN"
          fi
          echo "================================="

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use the GitHub App token if available, otherwise fallback to GITHUB_TOKEN
          token: ${{ steps.generate-token.outputs.token || secrets.GITHUB_TOKEN }}

      - name: Check if docs changed
        id: docs-changed
        if: github.event_name == 'pull_request'
        run: |
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha}} ${{ github.event.pull_request.head.sha}})
          
          if echo "$changed_files" | grep -E '^docs/integrations/|^docs/static/' > /dev/null; then
            echo "docs_changed=true" >> $GITHUB_OUTPUT
            echo "requires_cla=true" >> $GITHUB_OUTPUT
          else
            echo "docs_changed=false" >> $GITHUB_OUTPUT
            echo "requires_cla=false" >> $GITHUB_OUTPUT
          fi

      - name: Get PR info for comment events
        id: pr-info
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_PAT || secrets.GITHUB_TOKEN }}
          script: |
            if (context.payload.issue.pull_request) {
              const prNumber = context.payload.issue.number;
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber
              });
            
              const { data: files } = await github.rest.pulls.listFiles({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber
              });
            
              const hasDocsChanges = files.some(file => 
                file.filename.startsWith('docs/integrations/') ||
                file.filename.startsWith('static/images/')
              );
            
              // Check if PR author is a collaborator (safer alternative to org membership)
              let isClickHouseMember = false;
              try {
                const { data: collaboration } = await github.rest.repos.getCollaboratorPermissionLevel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  username: pr.user.login
                });
            
                // Consider admin, maintain, or write permissions as "member"
                isClickHouseMember = ['admin', 'maintain', 'write'].includes(collaboration.permission);
              } catch (error) {
                console.log(`Could not determine collaboration status for ${pr.user.login}: ${error.message}`);
                isClickHouseMember = false;
              }
            
              core.setOutput('pr_number', prNumber);
              core.setOutput('has_docs_changes', hasDocsChanges);
              core.setOutput('pr_head_sha', pr.head.sha);
              core.setOutput('pr_author', pr.user.login);
              core.setOutput('isClickHouseMember', isClickHouseMember);

              return { prNumber, hasDocsChanges, headSha: pr.head.sha, author: pr.user.login, isClickHouseMember };
            }
            
            return null;

      - name: Debug - CLA requirement check
        run: |
          echo "=== CLA REQUIREMENT DEBUG ==="
          echo "Event name: ${{ github.event_name }}"
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PR event - docs changed: ${{ steps.docs-changed.outputs.docs_changed }}"
            echo "PR event - requires CLA: ${{ steps.docs-changed.outputs.requires_cla }}"
          fi
          
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "Comment event - has docs changes: ${{ steps.pr-info.outputs.has_docs_changes }}"
            echo "Comment event - PR number: ${{ steps.pr-info.outputs.pr_number }}"
            echo "Comment event - PR author: ${{ steps.pr-info.outputs.pr_author }}"
            echo "Comment event - is ClickHouse member: ${{ steps.pr-info.outputs.isClickHouseMember }}"
          fi
          
          CLA_CONDITION="${{ (github.event_name == 'pull_request' && steps.docs-changed.outputs.requires_cla == 'true') || (github.event_name == 'issue_comment' && steps.pr-info.outputs.has_docs_changes == 'true') }}"
          echo "CLA workflow will run: $CLA_CONDITION"
          echo "================================="

      - name: Post CLA comment and block merge
        if: |
          ((github.event_name == 'pull_request' && steps.docs-changed.outputs.requires_cla == 'true') ||
           (github.event_name == 'issue_comment' && steps.pr-info.outputs.has_docs_changes == 'true'))
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token || secrets.GITHUB_TOKEN }}
          script: |
            console.log('=== CLA COMMENT STEP DEBUG ===');
            console.log('Event name:', context.eventName);
            
            let prNumber, prAuthor;
            
            if (context.eventName == 'pull_request') {
              prNumber = context.issue.number;
              prAuthor = '${{ github.event.pull_request.user.login }}';
              console.log('PR event - Number:', prNumber, 'Author:', prAuthor);
            } else {
              prNumber = ${{ steps.pr-info.outputs.pr_number || 'null' }};
              prAuthor = '${{ steps.pr-info.outputs.pr_author }}';
              console.log('Comment event - Number:', prNumber, 'Author:', prAuthor);
            }
            
            if (!prNumber || !prAuthor) {
              console.log('Missing PR number or author, skipping...');
              return;
            }
            
            console.log(`Processing PR #${prNumber} for author: ${prAuthor}`);
            
            try {
              // Check if CLA comment already exists
              console.log('Fetching existing comments...');
              const comments = await github.rest.issues.listComments({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              console.log(`Found ${comments.data.length} existing comments`);
            
              const existingClaComment = comments.data.find(comment => 
                (comment.user.login === 'github-actions[bot]' || comment.user.type === 'Bot') && 
                comment.body.includes('CLA Agreement Required - MERGE BLOCKED')
              );
            
              console.log('Existing CLA comment found:', !!existingClaComment);
            
              if (!existingClaComment && context.eventName === 'pull_request') {
                const claText = `# CLA Agreement Required - MERGE BLOCKED
            
              # Trademark License Addendum
            
              <details>
              <summary>Click to see Trademark License Addendum</summary>
            
              This Trademark License Addendum ("Addendum") shall, if You have opted 
              in by checking the appropriate box that references this Addendum, 
              supplement the terms of the Individual Contributor License Agreement
              between You and the Company ("Agreement"). Capitalized terms not
              defined herein shall have the meanings ascribed to them in the 
              Agreement.
            
              1. Grant of Trademark License. Subject to the terms and conditions 
              of this Addendum, You grant to the Company a revocable, worldwide,
              non-exclusive, non-sublicensable (except for contractors or agents
              acting on the Company's behalf, for whose compliance with this 
              Addendum Company agrees to be responsible), royalty-free, and non-transferable
              right to display the Partner Trademarks, solely for the purpose of
              marketing and promoting your Contribution (i) on the Company's website
              and in any Company in-product integrations page; and (ii) in 
              marketing, sales, and product materials for Company products. 
              "Partner Trademarks" mean Your employer's name and any employer 
              brand features (e.g., logo) you submit to the Company in connection with your
              Contribution.
              2. Legal authority. You represent that you are legally entitled to
              grant the above license. If your employer(s) has rights to 
              intellectual property in the Partner Trademarks, you represent that
              you have received permission to grant the above license on behalf 
              of that employer, or that your employer has executed a separate 
              agreement with the Company concerning the subject matter of this 
              Addendum.
              3. Conditions. The license in Section 1 is subject to the following
              conditions:
              i. The Company shall use the Partner Trademarks in accordance with
                 any reasonable trademark usage guidelines You provide;
              ii. You may revoke this license at any time upon thirty (30) days'
                  written notice to the Company, after which the Company shall use
                  commercially reasonable efforts to cease all further public
                  use of the Partner Trademarks (but may maintain uses in archived
                  web pages, changelogs, and previously distributed materials).
              iii. The Company acknowledges and agrees that it does not own the 
                   Partner Trademarks and that all goodwill derived from the use 
                   of the Partner Trademarks inures solely to benefit of the 
                   Partner Trademarks' owner(s).
              iv. The Company shall use the Partner Trademarks in a professional
                  manner consistent with industry standards and shall not use 
                  them in any way that would reasonably be expected to diminish 
                  their value or harm the reputation of the Partner Trademarks' 
                  owner(s). The Company's use of Partner Trademarks shall not 
                  imply endorsement, sponsorship, or affiliation beyond the 
                  existence of the Contribution in the Company's integration program.
              v. The Company will not use the Partner Trademarks in connection 
                 with search engine rankings, ad word purchases, or as part of a
                 trade name, business name, or Internet domain name.
            
              </details>
            
              **To unblock this PR, reply with exactly:**
            
              \`\`\`
              I have read and agree to the Contributor License Agreement.
              CLA-SIGNATURE: ${prAuthor}
              \`\`\``;
            
                console.log('Creating CLA comment...');
                await github.rest.issues.createComment({
                  issue_number: prNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: claText
                });
                console.log('CLA comment created successfully');
            
                console.log('Adding labels...');
                await github.rest.issues.addLabels({
                  issue_number: prNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ['cla-required', 'docs-changes']
                });
                console.log('Labels added successfully');
              } else {
                console.log('CLA comment already exists or not a pull request event');
              }
              console.log('=== END CLA COMMENT STEP DEBUG ===');
            } catch (error) {
              console.error('Error in CLA comment step:', error);
              throw error;
            }

      - name: Check CLA agreement and manage merge blocking
        if: |
          ((github.event_name == 'pull_request' && steps.docs-changed.outputs.requires_cla == 'true') ||
           (github.event_name == 'issue_comment' && steps.pr-info.outputs.has_docs_changes == 'true'))
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token || secrets.GITHUB_TOKEN }}
          script: |
            console.log('=== CLA AGREEMENT CHECK DEBUG ===');
            console.log('Event name:', context.eventName);
            
            let prNumber, prHeadSha, prAuthor;
            
            if (context.eventName === 'pull_request') {
              prNumber = context.issue.number;
              prHeadSha = '${{ github.event.pull_request.head.sha }}';
              prAuthor = '${{ github.event.pull_request.user.login }}';
              console.log('PR event - Number:', prNumber, 'SHA:', prHeadSha, 'Author:', prAuthor);
            } else {
              prNumber = ${{ steps.pr-info.outputs.pr_number || 'null' }};
              prHeadSha = '${{ steps.pr-info.outputs.pr_head_sha }}';
              prAuthor = '${{ steps.pr-info.outputs.pr_author }}';
              console.log('Comment event - Number:', prNumber, 'SHA:', prHeadSha, 'Author:', prAuthor);
            }
            
            if (!prNumber) {
              console.log('No PR number found, skipping...');
              return;
            }
            
            console.log(`Checking CLA agreement for PR #${prNumber}, author: ${prAuthor}`);
            
            try {
              // Get all comments to check for CLA agreement
              console.log('Fetching all comments for CLA check...');
              const comments = await github.rest.issues.listComments({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              console.log(`Found ${comments.data.length} comments to check`);
            
              const claAgreed = comments.data.some(comment => {
                const isAuthor = comment.user.login === prAuthor;
                const hasAgreement = comment.body.includes('I have read and agree to the Contributor License Agreement');
                const hasSignature = comment.body.includes(`CLA-SIGNATURE: ${prAuthor}`);
            
                if (isAuthor && (hasAgreement || hasSignature)) {
                  console.log(`Found potential CLA comment from ${comment.user.login}:`);
                  console.log('- Has agreement text:', hasAgreement);
                  console.log('- Has signature:', hasSignature);
                  console.log('- Comment body preview:', comment.body.substring(0, 100) + '...');
                }
            
                return isAuthor && hasAgreement && hasSignature;
              });
            
              console.log('CLA agreement status:', claAgreed);
            
              if (claAgreed) {
                console.log('CLA agreement found, removing blocking labels...');
            
                // CLA agreed - remove blocking labels and add approval
                try {
                  await github.rest.issues.removeLabel({
                    issue_number: prNumber,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: 'cla-required'
                  });
                  console.log('Removed cla-required label');
                } catch (e) {
                  console.log('Label cla-required not found or already removed:', e.message);
                }
            
                await github.rest.issues.addLabels({
                  issue_number: prNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ['cla-signed']
                });
                console.log('Added cla-signed label');
            
                // Post confirmation
                const confirmationExists = comments.data.some(comment => 
                  (comment.user.login === 'github-actions[bot]' || comment.user.type === 'Bot') && 
                  comment.body.includes('CLA Agreement Confirmed')
                );
                console.log('Confirmation comment exists:', confirmationExists);
            
                if (!confirmationExists) {
                  await github.rest.issues.createComment({
                    issue_number: prNumber,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: `## CLA Agreement Confirmed
            
                Thank you @${prAuthor}! Your response has been recorded.
            
                **Status:** Approved  
                **Date:** ${new Date().toISOString()}  
            
                This PR is now unblocked and can proceed with normal review!`
                  });
                  console.log('Posted confirmation comment');
                }
            
                console.log('CLA processing completed successfully');
              } else {
                console.log('CLA not agreed, keeping PR blocked');
                // CLA not agreed - keep it blocked
                core.setFailed('Documentation CLA agreement required before merge');
              }
              console.log('=== END CLA AGREEMENT CHECK DEBUG ===');
            } catch (error) {
              console.error('Error in CLA agreement check:', error);
              throw error;
            }
