name: Style check

on:
  pull_request:
    types:
      - synchronize
      - reopened
      - opened

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  vale:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: .

      - name: Install Vale
        run: |
          sudo snap install vale
          vale -v # Verify installation

      - name: Set up Python
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          uv python install 3.12

      - name: Get changed files and create report
        run: |
          # Create output directory
          mkdir -p reports

          # Start JSON file
          echo "{" > reports/changed_lines.json

          # Use git directly to find changed files in docs directory
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '^docs/.*\.(md|mdx)$' || echo "")

          echo "Changed files in docs directory:"
          echo "$changed_files"

          # Process each file
          first_file=true
          for file in $changed_files; do
            if [ -f "$file" ]; then
              echo "Processing file: $file"

              if [ "$first_file" = true ]; then
                first_file=false
              else
                echo "," >> reports/changed_lines.json
              fi

              echo "  \"$file\": [" >> reports/changed_lines.json

              # Get changed lines
              first_line=true
              git diff --unified=0 ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- "$file" | 
              grep -E "^@@" | 
              sed -E 's/^@@ -[0-9]+(,[0-9]+)? \+([0-9]+)(,[0-9]+)? @@.*$/\2/' |
              while read -r line_number; do
                echo "Found changed line $line_number in $file"

                if [ "$first_line" = true ]; then
                  first_line=false
                else
                  echo "," >> reports/changed_lines.json
                fi

                echo "    $line_number" >> reports/changed_lines.json
              done

              echo "  ]" >> reports/changed_lines.json
            fi
          done

          echo "}" >> reports/changed_lines.json

      - name: Debug Vale setup
        run: |
          # Show current directory structure
          find . -type d -name "ClickHouse" -o -name "styles"

          # Show the vale configuration
          cat .vale.ini

          # Check Vale's configuration
          vale ls-config

      - name: Check styles directory
        run: |
          echo "Checking styles directory structure:"
          ls -la .
          
          echo "Looking for ClickHouse style:"
          if [ -d "styles/ClickHouse" ]; then
            echo "✅ ClickHouse style directory found"
            ls -la styles/ClickHouse/
          else
            echo "❌ ClickHouse style directory NOT found"
            find styles/ -type d -maxdepth 2
          fi

      - name: Run vale on changed files
        run: |
          # Extract file names from the JSON report
          CHANGED_FILES=$(jq -r 'keys[]' reports/changed_lines.json)
          
          # Check if we have any files to process
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed files to analyze"
            exit 0
          fi
    
          vale --config='.vale.ini' \
          "${CHANGED_FILES}" \
          --output=scripts/vale_output_template.tmpl --no-exit > vale_output.log
          cat vale_output.log

      - name: Parse Vale output
        if: steps.changed_lines.outputs.changed_files
        env:
          LINES_CHANGED: ${{ steps.changed_lines.outputs.changed_lines }}
        run: |
          python scripts/vale_annotations.py --data=${LINES_CHANGED}
